### ISSUE TITLE
Multilingual BLOOM SGPT max_seq_length is the max_length of text input?

### ISSUE THREAD

**Issue by ennioferreirab** [Muennighoff/sgpt#17]
Model: bigscience-data/sgpt-bloom-1b7-nli
If I undestood correctly all tokens after max_seq_length gonna be truncated, or the model have a different way to treat it ?
Do you have a length number to recommend when compare symmetric, or asymmetric texts ?

**Comment by Muennighoff** [comment]
That model was trained with a max sequence length of 75, i.e.all texts longer than that were truncated to 75 tokens.
You can remove the 75 token limit at inference if you want. It may still work with longer texts.

Asymmetric texts tend to be longer, such as in the case of Retrieval with long documents. Hence this one https://huggingface.co/bigscience/sgpt-bloom-7b1-msmarco was trained with a max seq length of 300.

**Comment by ennioferreirab** [comment]
Thank you for fast reply !
