### ISSUE TITLE
Use SGPT 

### ISSUE THREAD

**Issue by Kartali-Mohamed** [Muennighoff/sgpt#20]
Hey 👋

I want to use sgpt in my website as sentence embedding for semantic search, but i can't understand how can i use both of cross-encoder and bi-encoder in one code, or i can use only one of  them?

**Comment by Muennighoff** [comment]
You could use both of them by using one or the other for re-ranking but it doesn't make a lot of sense, as the performance gains from combining them would be pretty small at significant compute cost. If you combine two models, you usually want one to be very cheap (e.g. BM25) and then have a second-stage expensive model.

I would do either:
- (BM25 ->) SGPT-CE
  - Add BM25 if you want it to be faster & have lots of documents and then re-rank only the top X with SGPT-CE
  - Will need a large GPU to run SGPT-CE
- SGPT-BE
  - If you want to cache the embeddings, you may need a lot of storage depending on how many documents you have
  - Will need a large GPU to run SGPT-BE

**Comment by Kartali-Mohamed** [comment]
Thanks a lot, it's very helpful 🙏
