### ISSUE TITLE
Training on unlabeled data (German)

### ISSUE THREAD

**Issue by anastasiia-ps** [Muennighoff/sgpt#26]
Hey, I have a specific domain and unlabeled data. As I see, SGPT accepts only labeled data. Do you have experience with using artificially created labeled data? For example with GPL method? Moreover is there any good pre-trained model variant for German that can be fine-tuned?

**Comment by Muennighoff** [comment]
Hey! If you use SGPT-CE you can directly use the model without labeling, however, its inference cost is very high and you do not get embeddings.

For SGPT-BE you need labeled positive pairs & for top performance also labeled negative pairs. I have not experimented with artificially created labeled data. I would first experiment with published models to confirm that they do not perform well on your task. Then you could try fine-tuning e.g. https://huggingface.co/dbmdz/german-gpt2. If you do not have a high quality fine-tuning dataset in German, I would try just fine-tuning on an English one. Usually the capabilities transfer across languages.
