### ISSUE TITLE
Model taken down?

### ISSUE THREAD

**Issue by extradosages** [Muennighoff/sgpt#28]
Seems like the [huggingface models](https://huggingface.co/Muennighoff) are all gone. Did something unfortunate happen?

**Comment by addieindustry** [comment]
models have been gone suddenly, from where we can access it

**Comment by Muennighoff** [comment]
I think it's related to this bug: https://twitter.com/huggingface/status/1655760648926642178
I don't have a backup of the models unfortunately, so will need to wait for that bug to be resolved :(

**Comment by albertbn** [comment]
As a temporary solution one could use the **cached weights**. On my machine the path looks something like that: 

`/home/$USER/.cache/huggingface/hub/models--Muennighoff--SGPT-2.7B-weightedmean-msmarco-specb-bitfit/snapshots/44ec091e09d0366b9681dc853f88bfb619fedd19/`

**Comment by Muennighoff** [comment]
I think the models are back online, sorry for the disruption!

**Comment by extradosages** [comment]
Hah, wonderful.

I should otherwise take the opportunity to thank you @Muennighoff for you work.
So thank you.
