### ISSUE TITLE
What is the core code of unsupervised embedding of SGPT? 

### ISSUE THREAD

**Issue by guotong1988** [Muennighoff/sgpt#34]
@Muennighoff Thank you very much!

**Comment by Muennighoff** [comment]
Essentially this script: https://github.com/Muennighoff/sgpt/blob/main/crossencoder/beir/sgptce.py

**Comment by Muennighoff** [comment]
But it's equivalent to this simplified code: https://github.com/Muennighoff/sgpt#asymmetric-semantic-search-ce

The py script I sent above just has some additional batching and benchmarking overhead
