### ISSUE TITLE
Training scripts have wrong name of gpt-neo-125m

### ISSUE THREAD

**Issue by aksj98** [Muennighoff/sgpt#38]
Hi! The Huggingface name of GPT-neo-125m is gpt-neo-125m (https://huggingface.co/EleutherAI/gpt-neo-125m) , in the training script commands, it is referenced as gpt-neo-125M everywhere, which throws errors, fixed in #37

**Comment by Muennighoff** [comment]
Can you show me the errors it throws for you?
For me it works just fine; I think the loading is case-insensitive:
```python
!pip install -q transformers
from transformers import AutoTokenizer, AutoModel
AutoModel.from_pretrained("EleutherAI/GPT-NEO-125M")
```

**Comment by aksj98** [comment]
<img width="694" alt="image" src="https://github.com/Muennighoff/sgpt/assets/18054942/dac9adae-6610-412c-8d84-b17e4a1e7c2a">


And I don't have a file/folder with that name on the VM - works with "125m" though
